[workspace]
members = [
#    "nican",
    "rs-can",
    "zlgcan.new",
    "zlgcan",
]

resolver = "2"

[workspace.dependencies]
thiserror = "1"
log = "0"
dlopen2 = "0.7"
bitflags = "2.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
dotenvy = "0.15"
isotp-rs = { version = "0.2.1" }

# dev-dependencies
anyhow = "1"
hex-literal = "0.4"
bin_file = "0.1"
crc = "3.2"
ecu-uds = { version = "0.1.5" }
