[package]
name = "rs-can"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
description = "A Nican driver."
homepage = "https://github.com/zhuyu4839/rust-can"
repository = "https://github.com/zhuyu4839/rust-can"

[dependencies]
log = { workspace = true }
bitflags = { workspace = true }
thiserror = { workspace = true }
isotp-rs = { workspace = true }

[features]
async = []
