[package]
name = "nican"
version = "0.1.0"
edition = "2021"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
license = "GPL-3.0"
description = "A Nican driver."
homepage = "https://github.com/zhuyu4839/rs-can"
repository = "https://github.com/zhuyu4839/rs-can"

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
isotp-rs = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[build-dependencies]
bindgen = "0.70"
