[package]
name = "nican"
version = "0.1.1-alpha0"
edition = "2021"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
license = "GPL-3.0"
description = "A Nican driver."
homepage = "https://github.com/zhuyu4839/rust-can"
repository = "https://github.com/zhuyu4839/rust-can"

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
isotp-rs = { workspace = true }
rs-can = { path = "../rs-can" }

[dev-dependencies]
anyhow = { workspace = true }
ecu-uds = { path = "../../ecu-proto-rs/ecu-uds" }

[build-dependencies]
bindgen = "0.70"
